### ISSUE TITLE
get next line subject change

### ISSUE THREAD

**Issue by mvaldes42** [markveligod/exam#4]
There has been a change in get next line subject(at least for Paris), it is now `char *get_next_line(int fd);` must return the end '\n' if there is one at the end of the line, return (NULL) instead of (-1) in case of an error, and is compiled with `-D BUFFER_SIZE=xx` with BUFFER_SIZE that must be used in the read call.

**Comment by markveligod** [comment]
If there are any changes in the subject, do fork and pull request in master branch
